### ISSUE TITLE
升级到最新版后，无法访问管理后台

### ISSUE THREAD

**Issue by ghost** [skywalker512/FlarumChina#14]
Fatal error: Uncaught Error: Call to undefined function Flarum\Extension\finfo_file() in /www/wwwroot/bbs.letitfly.me/vendor/flarum/core/src/Extension/Extension.php:186 Stack trace: #0 /www/wwwroot/bbs.letitfly.me/vendor/flarum/core/src/Extension/Extension.php(265): Flarum\Extension\Extension->getIcon() #1 /www/wwwroot/bbs.letitfly.me/vendor/illuminate/support/Collection.php(968): Flarum\Extension\Extension->toArray() #2 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(Flarum\Extension\Extension)) #3 /www/wwwroot/bbs.letitfly.me/vendor/illuminate/support/Collection.php(969): array_map(Object(Closure), Array) #4 /www/wwwroot/bbs.letitfly.me/vendor/flarum/core/src/Admin/Controller/WebAppController.php(64): Illuminate\Support\Collection->toArray() #5 /www/wwwroot/bbs.letitfly.me/vendor/flarum/core/src/Http/Controller/AbstractWebAppController.php(37): Flarum\Admin\Controller\WebAppController->getView(Object(Zend\Stratigility\Http\Request)) #6 /www/wwwroot/bbs.letitfly.me/vendor/flarum/co in /www/wwwroot/bbs.letitfly.me/vendor/flarum/core/src/Extension/Extension.phpon line 186

**Comment by ghost** [comment]
是迁移后未安装 Flieinfo 导致的问题，打扰大佬了。
